name: Git hub pipeline demo

on:
    push:
        branches:
            - main

jobs:
    demo-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: action/checkout@v2

            - name: print message
              run: echo "Welcome to github action"

